// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMOR3MN8p50i8w7ok1NUsJrTRofS22I2o',
    appId: '1:25203293550:web:f3b5cc909f99e1b40b157f',
    messagingSenderId: '25203293550',
    projectId: 'liu-stoma',
    authDomain: 'liu-stoma.firebaseapp.com',
    storageBucket: 'liu-stoma.firebasestorage.app',
    measurementId: 'G-7F6C3BMBK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkW5kBQXQU8E7bzos-p98ZsRyZpc1Zlyk',
    appId: '1:25203293550:android:e3e8bee629fe32980b157f',
    messagingSenderId: '25203293550',
    projectId: 'liu-stoma',
    storageBucket: 'liu-stoma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3X5RXd2nVLlBTfWEsJBnC9ilWMQM6TCA',
    appId: '1:25203293550:ios:3e5f502f746a954c0b157f',
    messagingSenderId: '25203293550',
    projectId: 'liu-stoma',
    storageBucket: 'liu-stoma.firebasestorage.app',
    iosBundleId: 'com.example.liuStoma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3X5RXd2nVLlBTfWEsJBnC9ilWMQM6TCA',
    appId: '1:25203293550:ios:3e5f502f746a954c0b157f',
    messagingSenderId: '25203293550',
    projectId: 'liu-stoma',
    storageBucket: 'liu-stoma.firebasestorage.app',
    iosBundleId: 'com.example.liuStoma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMOR3MN8p50i8w7ok1NUsJrTRofS22I2o',
    appId: '1:25203293550:web:d160f95b83e5af3e0b157f',
    messagingSenderId: '25203293550',
    projectId: 'liu-stoma',
    authDomain: 'liu-stoma.firebaseapp.com',
    storageBucket: 'liu-stoma.firebasestorage.app',
    measurementId: 'G-RJTJWTCGFC',
  );

}